/**
 * Jurisdiction configuration for Regulation S compliance.
 *
 * RESTRICTED_COUNTRIES: US + OFAC comprehensively sanctioned jurisdictions.
 * This list should be reviewed periodically against current OFAC SDN guidance.
 *
 * ISO 3166-1 alpha-2 codes.
 */
export const RESTRICTED_COUNTRY_CODES = new Set([
  "US", // United States
  "CU", // Cuba
  "IR", // Iran
  "KP", // North Korea (DPRK)
  "SY", // Syria
  "RU", // Russia
  "BY", // Belarus
  "MM", // Myanmar (Burma)
  "VE", // Venezuela (limited sanctions, included conservatively)
]);

/**
 * Full country list for the dropdown (ISO 3166-1).
 * Each entry: { code, name, restricted }
 */
export const COUNTRIES: { code: string; name: string; restricted: boolean }[] = [
  { code: "AF", name: "Afghanistan", restricted: false },
  { code: "AL", name: "Albania", restricted: false },
  { code: "DZ", name: "Algeria", restricted: false },
  { code: "AD", name: "Andorra", restricted: false },
  { code: "AO", name: "Angola", restricted: false },
  { code: "AG", name: "Antigua and Barbuda", restricted: false },
  { code: "AR", name: "Argentina", restricted: false },
  { code: "AM", name: "Armenia", restricted: false },
  { code: "AU", name: "Australia", restricted: false },
  { code: "AT", name: "Austria", restricted: false },
  { code: "AZ", name: "Azerbaijan", restricted: false },
  { code: "BS", name: "Bahamas", restricted: false },
  { code: "BH", name: "Bahrain", restricted: false },
  { code: "BD", name: "Bangladesh", restricted: false },
  { code: "BB", name: "Barbados", restricted: false },
  { code: "BY", name: "Belarus", restricted: true },
  { code: "BE", name: "Belgium", restricted: false },
  { code: "BZ", name: "Belize", restricted: false },
  { code: "BJ", name: "Benin", restricted: false },
  { code: "BT", name: "Bhutan", restricted: false },
  { code: "BO", name: "Bolivia", restricted: false },
  { code: "BA", name: "Bosnia and Herzegovina", restricted: false },
  { code: "BW", name: "Botswana", restricted: false },
  { code: "BR", name: "Brazil", restricted: false },
  { code: "BN", name: "Brunei", restricted: false },
  { code: "BG", name: "Bulgaria", restricted: false },
  { code: "BF", name: "Burkina Faso", restricted: false },
  { code: "BI", name: "Burundi", restricted: false },
  { code: "CV", name: "Cabo Verde", restricted: false },
  { code: "KH", name: "Cambodia", restricted: false },
  { code: "CM", name: "Cameroon", restricted: false },
  { code: "CA", name: "Canada", restricted: false },
  { code: "CF", name: "Central African Republic", restricted: false },
  { code: "TD", name: "Chad", restricted: false },
  { code: "CL", name: "Chile", restricted: false },
  { code: "CN", name: "China", restricted: false },
  { code: "CO", name: "Colombia", restricted: false },
  { code: "KM", name: "Comoros", restricted: false },
  { code: "CG", name: "Congo", restricted: false },
  { code: "CD", name: "Congo (DRC)", restricted: false },
  { code: "CR", name: "Costa Rica", restricted: false },
  { code: "CI", name: "Côte d'Ivoire", restricted: false },
  { code: "HR", name: "Croatia", restricted: false },
  { code: "CU", name: "Cuba", restricted: true },
  { code: "CY", name: "Cyprus", restricted: false },
  { code: "CZ", name: "Czech Republic", restricted: false },
  { code: "DK", name: "Denmark", restricted: false },
  { code: "DJ", name: "Djibouti", restricted: false },
  { code: "DM", name: "Dominica", restricted: false },
  { code: "DO", name: "Dominican Republic", restricted: false },
  { code: "EC", name: "Ecuador", restricted: false },
  { code: "EG", name: "Egypt", restricted: false },
  { code: "SV", name: "El Salvador", restricted: false },
  { code: "GQ", name: "Equatorial Guinea", restricted: false },
  { code: "ER", name: "Eritrea", restricted: false },
  { code: "EE", name: "Estonia", restricted: false },
  { code: "SZ", name: "Eswatini", restricted: false },
  { code: "ET", name: "Ethiopia", restricted: false },
  { code: "FJ", name: "Fiji", restricted: false },
  { code: "FI", name: "Finland", restricted: false },
  { code: "FR", name: "France", restricted: false },
  { code: "GA", name: "Gabon", restricted: false },
  { code: "GM", name: "Gambia", restricted: false },
  { code: "GE", name: "Georgia", restricted: false },
  { code: "DE", name: "Germany", restricted: false },
  { code: "GH", name: "Ghana", restricted: false },
  { code: "GR", name: "Greece", restricted: false },
  { code: "GD", name: "Grenada", restricted: false },
  { code: "GT", name: "Guatemala", restricted: false },
  { code: "GN", name: "Guinea", restricted: false },
  { code: "GW", name: "Guinea-Bissau", restricted: false },
  { code: "GY", name: "Guyana", restricted: false },
  { code: "HT", name: "Haiti", restricted: false },
  { code: "HN", name: "Honduras", restricted: false },
  { code: "HK", name: "Hong Kong", restricted: false },
  { code: "HU", name: "Hungary", restricted: false },
  { code: "IS", name: "Iceland", restricted: false },
  { code: "IN", name: "India", restricted: false },
  { code: "ID", name: "Indonesia", restricted: false },
  { code: "IR", name: "Iran", restricted: true },
  { code: "IQ", name: "Iraq", restricted: false },
  { code: "IE", name: "Ireland", restricted: false },
  { code: "IL", name: "Israel", restricted: false },
  { code: "IT", name: "Italy", restricted: false },
  { code: "JM", name: "Jamaica", restricted: false },
  { code: "JP", name: "Japan", restricted: false },
  { code: "JO", name: "Jordan", restricted: false },
  { code: "KZ", name: "Kazakhstan", restricted: false },
  { code: "KE", name: "Kenya", restricted: false },
  { code: "KI", name: "Kiribati", restricted: false },
  { code: "KW", name: "Kuwait", restricted: false },
  { code: "KG", name: "Kyrgyzstan", restricted: false },
  { code: "LA", name: "Laos", restricted: false },
  { code: "LV", name: "Latvia", restricted: false },
  { code: "LB", name: "Lebanon", restricted: false },
  { code: "LS", name: "Lesotho", restricted: false },
  { code: "LR", name: "Liberia", restricted: false },
  { code: "LY", name: "Libya", restricted: false },
  { code: "LI", name: "Liechtenstein", restricted: false },
  { code: "LT", name: "Lithuania", restricted: false },
  { code: "LU", name: "Luxembourg", restricted: false },
  { code: "MO", name: "Macau", restricted: false },
  { code: "MG", name: "Madagascar", restricted: false },
  { code: "MW", name: "Malawi", restricted: false },
  { code: "MY", name: "Malaysia", restricted: false },
  { code: "MV", name: "Maldives", restricted: false },
  { code: "ML", name: "Mali", restricted: false },
  { code: "MT", name: "Malta", restricted: false },
  { code: "MH", name: "Marshall Islands", restricted: false },
  { code: "MR", name: "Mauritania", restricted: false },
  { code: "MU", name: "Mauritius", restricted: false },
  { code: "MX", name: "Mexico", restricted: false },
  { code: "FM", name: "Micronesia", restricted: false },
  { code: "MD", name: "Moldova", restricted: false },
  { code: "MC", name: "Monaco", restricted: false },
  { code: "MN", name: "Mongolia", restricted: false },
  { code: "ME", name: "Montenegro", restricted: false },
  { code: "MA", name: "Morocco", restricted: false },
  { code: "MZ", name: "Mozambique", restricted: false },
  { code: "MM", name: "Myanmar", restricted: true },
  { code: "NA", name: "Namibia", restricted: false },
  { code: "NR", name: "Nauru", restricted: false },
  { code: "NP", name: "Nepal", restricted: false },
  { code: "NL", name: "Netherlands", restricted: false },
  { code: "NZ", name: "New Zealand", restricted: false },
  { code: "NI", name: "Nicaragua", restricted: false },
  { code: "NE", name: "Niger", restricted: false },
  { code: "NG", name: "Nigeria", restricted: false },
  { code: "KP", name: "North Korea", restricted: true },
  { code: "MK", name: "North Macedonia", restricted: false },
  { code: "NO", name: "Norway", restricted: false },
  { code: "OM", name: "Oman", restricted: false },
  { code: "PK", name: "Pakistan", restricted: false },
  { code: "PW", name: "Palau", restricted: false },
  { code: "PS", name: "Palestine", restricted: false },
  { code: "PA", name: "Panama", restricted: false },
  { code: "PG", name: "Papua New Guinea", restricted: false },
  { code: "PY", name: "Paraguay", restricted: false },
  { code: "PE", name: "Peru", restricted: false },
  { code: "PH", name: "Philippines", restricted: false },
  { code: "PL", name: "Poland", restricted: false },
  { code: "PT", name: "Portugal", restricted: false },
  { code: "QA", name: "Qatar", restricted: false },
  { code: "RO", name: "Romania", restricted: false },
  { code: "RU", name: "Russia", restricted: true },
  { code: "RW", name: "Rwanda", restricted: false },
  { code: "KN", name: "Saint Kitts and Nevis", restricted: false },
  { code: "LC", name: "Saint Lucia", restricted: false },
  { code: "VC", name: "Saint Vincent and the Grenadines", restricted: false },
  { code: "WS", name: "Samoa", restricted: false },
  { code: "SM", name: "San Marino", restricted: false },
  { code: "ST", name: "São Tomé and Príncipe", restricted: false },
  { code: "SA", name: "Saudi Arabia", restricted: false },
  { code: "SN", name: "Senegal", restricted: false },
  { code: "RS", name: "Serbia", restricted: false },
  { code: "SC", name: "Seychelles", restricted: false },
  { code: "SL", name: "Sierra Leone", restricted: false },
  { code: "SG", name: "Singapore", restricted: false },
  { code: "SK", name: "Slovakia", restricted: false },
  { code: "SI", name: "Slovenia", restricted: false },
  { code: "SB", name: "Solomon Islands", restricted: false },
  { code: "SO", name: "Somalia", restricted: false },
  { code: "ZA", name: "South Africa", restricted: false },
  { code: "KR", name: "South Korea", restricted: false },
  { code: "SS", name: "South Sudan", restricted: false },
  { code: "ES", name: "Spain", restricted: false },
  { code: "LK", name: "Sri Lanka", restricted: false },
  { code: "SD", name: "Sudan", restricted: false },
  { code: "SR", name: "Suriname", restricted: false },
  { code: "SE", name: "Sweden", restricted: false },
  { code: "CH", name: "Switzerland", restricted: false },
  { code: "SY", name: "Syria", restricted: true },
  { code: "TW", name: "Taiwan", restricted: false },
  { code: "TJ", name: "Tajikistan", restricted: false },
  { code: "TZ", name: "Tanzania", restricted: false },
  { code: "TH", name: "Thailand", restricted: false },
  { code: "TL", name: "Timor-Leste", restricted: false },
  { code: "TG", name: "Togo", restricted: false },
  { code: "TO", name: "Tonga", restricted: false },
  { code: "TT", name: "Trinidad and Tobago", restricted: false },
  { code: "TN", name: "Tunisia", restricted: false },
  { code: "TR", name: "Turkey", restricted: false },
  { code: "TM", name: "Turkmenistan", restricted: false },
  { code: "TV", name: "Tuvalu", restricted: false },
  { code: "UG", name: "Uganda", restricted: false },
  { code: "UA", name: "Ukraine", restricted: false },
  { code: "AE", name: "United Arab Emirates", restricted: false },
  { code: "GB", name: "United Kingdom", restricted: false },
  { code: "US", name: "United States", restricted: true },
  { code: "UY", name: "Uruguay", restricted: false },
  { code: "UZ", name: "Uzbekistan", restricted: false },
  { code: "VU", name: "Vanuatu", restricted: false },
  { code: "VA", name: "Vatican City", restricted: false },
  { code: "VE", name: "Venezuela", restricted: true },
  { code: "VN", name: "Vietnam", restricted: false },
  { code: "YE", name: "Yemen", restricted: false },
  { code: "ZM", name: "Zambia", restricted: false },
  { code: "ZW", name: "Zimbabwe", restricted: false },
];

/** Cookie name for jurisdiction clearance */
export const JURISDICTION_COOKIE = "portal_jurisdiction";
